pro_platform/auth_block/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    LoginView,
    LogoutView, RegisterView,
)
from django.contrib.auth.views import (
    # LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = "auth_block"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("me/", TemplateView.as_view(template_name="auth_block/me.html"), name="about-me"),


    path('password-reset/', PasswordResetView.as_view(template_name='auth_block/password_reset.html'),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='auth_block/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='auth_block/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='auth_block/password_reset_complete.html'),
         name='password_reset_complete'),
]

pro_platform/pro_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name='main_index'),

    path('auth/', include('auth_block.urls')),
    path('shop_projects/', include('shop_projects.urls')),
    path('my_projects/', include('my_projects.urls')),

    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

    # adding media static for url searching
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_platform/shop_projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views.index import ShopIndexView, get_task_info
from .views.projects import (
    ProjectsListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)
from .views.categories import (
    CategoriesListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)
from .views.creators import (
    CreatorsListView,
    CreatorDetailView,
    CreatorCreateView,
    CreatorUpdateView,
    CreatorDeleteView,
)

from .views.donats import (
    DonatsListView,
    DonatDetailView,
    DonatCreateView,
    DonatUpdateView,
    DonatDeleteView,
)
from .views.orders import (
    order_list_view,
    order_detail_view,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
)

app_name = "shop_projects"

urlpatterns = [
    path('', ShopIndexView.as_view(), name="index"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task-id"),

    path('projects', ProjectsListView.as_view(), name="projects"),
    path("projects/create/", ProjectCreateView.as_view(), name="create-project"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-details"),
    path("projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="update-project"),
    path("projects/<int:pk>/confirm-delete/", ProjectDeleteView.as_view(), name="confirm-delete-project"),

    path('categories', CategoriesListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-details"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),

    path('creators', CreatorsListView.as_view(), name="creators"),
    path("creators/create/", CreatorCreateView.as_view(), name="create-creator"),
    path("creators/<int:pk>/", CreatorDetailView.as_view(), name="creator-details"),
    path("creators/<int:pk>/update/", CreatorUpdateView.as_view(), name="update-creator"),
    path("creators/<int:pk>/confirm-delete/", CreatorDeleteView.as_view(), name="confirm-delete-creator"),

    path('donats', DonatsListView.as_view(), name="donats"),
    path("donats/create/", DonatCreateView.as_view(), name="create-donat"),
    path("donats/<int:pk>/", DonatDetailView.as_view(), name="donat-details"),
    path("donats/<int:pk>/update/", DonatUpdateView.as_view(), name="update-donat"),
    path("donats/<int:pk>/confirm-delete/", DonatDeleteView.as_view(), name="confirm-delete-donat"),

    path('orders', order_list_view, name="orders"),
    path("orders/create/", OrderCreateView.as_view(), name="create-order"),
    path("orders/<int:pk>/", order_detail_view, name="order-details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="update-order"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="confirm-delete-order"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pro_platform/shop_projects/models.py
from django.db import models
from django.contrib.auth.models import User


class BaseModel(models.Model):  # base class should subclass 'django.db.models.Model'

    class Status(models.IntegerChoices):
        ARCHIVED = 0
        AVAILABLE = 1

    status = models.IntegerField(
        choices=Status.choices,
        default=Status.AVAILABLE
    )

    class Meta:
        abstract = True  # Set this model as Abstract


class Category(BaseModel):
    class Meta:
        verbose_name_plural = "categories"

    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


# from shop_projects_app.models import Category
class Creator(BaseModel):
    class Meta:
        verbose_name_plural = "creators"

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField()

    def __str__(self):
        return f"Creator {self.user}"


class Project(BaseModel):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name="projects_for_cats",  # Important  arg!
    )  # Если удалим Category, то Project не дропнится

    # new fields
    creator = models.ForeignKey(
        Creator,
        on_delete=models.PROTECT,
        null=True,
        related_name="projects_for_creators"
    )
    url = models.CharField(max_length=150, null=True)
    other_contributors = models.TextField(null=True)
    # archived = models.BooleanField(default=False)

    # Time fields
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Product <№{self.id}, {self.name!r}>"


class Order(BaseModel):
    class Meta:
        verbose_name_plural = "orders"

    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
    )
    projects = models.ManyToManyField(
        Project,
        related_name="orders",
    )
    promocode = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class OrderPaymentDetails(models.Model):
    class Meta:
        verbose_name_plural = "Order Payment Details"

    class Status(models.IntegerChoices):
        PENDING = 0
        CONFIRMED = 1

    order = models.OneToOneField(
        Order,
        on_delete=models.CASCADE,
        related_name="payment_details",
    )
    payed_at = models.DateTimeField(
        blank=True,
        null=True,
    )
    card_ends_with = models.CharField(max_length=5, blank=True)
    status = models.IntegerField(
        choices=Status.choices,
        default=Status.PENDING,
    )


class Donat(BaseModel):
    class Meta:
        verbose_name_plural = "donats"

    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
    )
    projects = models.ManyToManyField(
        Project,
        related_name="donats",
        # on_delete=models.PROTECT,
    )
    money = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

pro_platform/shop_projects/views/categories.py
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop_projects.forms import CategoryForm
from shop_projects.models import Category


class CategoriesListView(ListView):
    queryset = (
        Category
        .objects
        .filter(status=Category.Status.AVAILABLE)
        .order_by("id")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
    }


class CategoryDetailView(DetailView):
    queryset = (
        Category
        .objects
        .order_by("id")
        .prefetch_related("projects_for_cats")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
        "back_url_to_all_objs": 'shop_projects:categories',
    }


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy("shop_projects:categories")

    extra_context = {
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
    }


class CategoryUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Category
    form_class = CategoryForm

    extra_context = {
        "class_name": Category._meta.object_name.lower(),
        "class_name_plural": Category._meta.verbose_name_plural,
    }

    def get_success_url(self):
        return reverse(
            "shop_projects:category-details",
            kwargs={
                "pk": self.object.pk,
            }
        )


class CategoryDeleteView(DeleteView):
    success_url = reverse_lazy("shop_projects:categories")
    queryset = (
        Category
        .objects
        .filter(status=Category.Status.AVAILABLE)
        .all()
    )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Category.Status.ARCHIVED  # .value
        self.object.save()
        return redirect(success_url)

pro_platform/shop_projects/views/creators.py
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop_projects.forms import CreatorForm
from shop_projects.models import Creator


class CreatorsListView(ListView):
    queryset = (
        Creator
        .objects
        .filter(status=Creator.Status.AVAILABLE)
        .select_related("user")
        .order_by("id")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
    }


class CreatorDetailView(DetailView):
    queryset = (
        Creator
        .objects
        .order_by("id")
        .select_related("user")
        .prefetch_related("projects_for_creators")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
        "back_url_to_all_objs": 'shop_projects:creators',
    }


class CreatorCreateView(CreateView):
    model = Creator
    form_class = CreatorForm
    success_url = reverse_lazy("shop_projects:creators")

    extra_context = {
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
    }


class CreatorUpdateView(UpdateView):
    template_name_suffix = "_update_form"
    model = Creator
    form_class = CreatorForm

    extra_context = {
        "class_name": Creator._meta.object_name.lower(),
        "class_name_plural": Creator._meta.verbose_name_plural,
    }

    def get_success_url(self):
        return reverse(
            "shop_projects:creator-details",
            kwargs={
                "pk": self.object.pk,
            }
        )


class CreatorDeleteView(DeleteView):
    success_url = reverse_lazy("shop_projects:creators")
    queryset = (
        Creator
        .objects
        .filter(status=Creator.Status.AVAILABLE)
        .all()
    )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Creator.Status.ARCHIVED
        self.object.save()
        return redirect(success_url)

pro_platform/shop_projects/views/donats.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop_projects.forms import DonatForm
from shop_projects.models import Donat


class DonatsListView(LoginRequiredMixin, ListView):
    queryset = (
        Donat
        .objects
        .filter(status=Donat.Status.AVAILABLE)
        .order_by("money")
        .select_related("user")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
    }


class DonatDetailView(UserPassesTestMixin, DetailView):

    def test_func(self):
        return self.request.user.is_staff

    queryset = (
        Donat
        .objects
        .order_by("id")
        .select_related("user")
        .prefetch_related("projects")
        .all()
    )

    extra_context = {
        "categories": queryset,
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
        "back_url_to_all_objs": 'shop_projects:donats',
    }


class DonatCreateView(LoginRequiredMixin, CreateView):
    model = Donat
    form_class = DonatForm
    success_url = reverse_lazy("shop_projects:donats")

    extra_context = {
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
    }


class DonatUpdateView(LoginRequiredMixin, UpdateView):
    template_name_suffix = "_update_form"
    model = Donat
    form_class = DonatForm

    extra_context = {
        "class_name": Donat._meta.object_name.lower(),
        "class_name_plural": Donat._meta.verbose_name_plural,
    }

    def get_success_url(self):
        return reverse(
            "shop_projects:donat-details",
            kwargs={
                "pk": self.object.pk,
            }
        )


class DonatDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "shop_projects.delete_donat"

    success_url = reverse_lazy("shop_projects:donats")
    queryset = (
        Donat
        .objects
        .filter(status=Donat.Status.AVAILABLE)
        .all()
    )

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.status = Donat.Status.ARCHIVED
        self.object.save()
        return redirect(success_url)


if __name__ == "__main__":
    print(DonatDetailView.mro())

pro_platform/shop_projects/views/index.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from celery.result import AsyncResult
from django.http import HttpResponse, HttpRequest, JsonResponse

from shop_projects.tasks import notify_order_saved


class ShopIndexView(TemplateView):
    template_name = "shop_projects/index.html"


@login_required
def get_task_info(request: HttpRequest, task_id: str) -> HttpResponse:
    task_result: AsyncResult = notify_order_saved.AsyncResult(task_id)

    return JsonResponse({
        "task_id": task_result.id,
        "task_status": task_result.status,
        "name": task_result.name,
    })

pro_platform/shop_projects/templates/shop_projects/category_confirm_delete.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Archive {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ object.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive {{ class_name }} #{{ object.pk }}
    with name <code>{{ object.name }}</code>?
  </div>

  <form class="my-2" method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:category-details' pk=object.pk %}">
        Back to {{ class_name }} details</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/category_detail.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  {{ class_name_plural }} #{{ object.pk }}
{% endblock %}

{% block body %}
    <div class="my-3">
        <h1>{{ class_name }} #{{ object.pk }} detail:</h1>
        <h2><code>{{ object.name }}</code></h2>
    </div>

    <h3>Description:</h3>
    <p>{{ object.description }}</p>

    <h3>Projects:</h3>
    <ul>
      {% for project in object.projects_for_cats.all %}
        <li>{{ project.name }}</li>
      {% endfor %}
    </ul>

    <div class="my-2">
      <a class="btn btn-success"
         href="{% url 'shop_projects:update-category' pk=object.pk %}">
          Update</a>
    <a class="btn btn-warning"
       href="{% url 'shop_projects:confirm-delete-category' pk=object.pk %}">
       Archive</a>
    </div>

  <div>
    <a class="btn btn-secondary"
       href="{% url back_url_to_all_objs %}">
       To all {{ class_name_plural }}</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/category_list.html
{% extends 'shop_projects/index.html' %}

{% block title %}
{{ class_name_plural }}
{% endblock %}

{% block body %}
<h1>{{ class_name_plural }}:</h1>
<div>
    <ul>
        {% for object in object_list %}
        <li><a
                href="{% url 'shop_projects:category-details' pk=object.pk %}">
            {{ object.name }}</a></li>
        {% endfor %}
    </ul>
</div>

<a class="btn btn-primary my-2"
   href="{% url 'shop_projects:create-category' %}">
    Create new {{ class_name }}</a>

<div>
    {% include 'macros/back_to_index.html' %}
</div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/category_update_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Update {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h2>Update {{ class_name }} #{{ object.pk }} with name <code>{{ object.name }}</code></h2>
  <form class="my-3" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Update">
  </form>

  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:category-details' pk=object.pk %}">
      Back to {{ class_name }} details</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/donat_confirm_delete.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Archive {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ object.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive {{ class_name }} #{{ object.pk }}
    with name <code>{{ object.name }}</code>?
  </div>

  <form class="my-2" method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:donat-details' pk=object.pk %}">
        Back to {{ class_name }} details</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/donat_detail.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  {{ class_name_plural }} #{{ object.pk }}
{% endblock %}

{% block body %}
    <div class="my-3">
        Donater: <strong>{{ object.user }}</strong>
        <br>
        Sum: <i>${{ object.money }}</i>
        <br>
        Date: {{ object.created_at }}
    </div>

    <h3>Projects:</h3>
    <ul>
      {% for project in object.projects.all %}
        <li>{{ project.name }}</li>
      {% endfor %}
    </ul>

    <div class="my-2">
      <a class="btn btn-success"
         href="{% url 'shop_projects:update-donat' pk=object.pk %}">
          Update</a>


        {% if perms.shop_projects.delete_donat %}
        <a class="btn btn-warning"
           href="{% url 'shop_projects:confirm-delete-donat' pk=object.pk %}">
           Archive</a>
        {% endif %}

        </div>

  <div>
    <a class="btn btn-secondary"
       href="{% url back_url_to_all_objs %}">
       To all {{ class_name_plural }}</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/donat_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Create {{ class_name }}
{% endblock %}

{% block body %}
    <h1>Create a new {{ class_name }}:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/order_confirm_delete.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Archive {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ object.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive {{ class_name }} #{{ object.pk }}
    with name <code>{{ object.name }}</code>?
  </div>

  <form class="my-2" method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:order-details' pk=object.pk %}">
        Back to {{ class_name }} details</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/order_detail.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  {{ class_name_plural }} #{{ object.pk }}
{% endblock %}

{% block body %}


      {% for object, aggr_proj_sum in query_list %}

        <div class="my-3">
            <h1>{{ class_name }} #{{ object.pk }} detail:</h1>
            Customer: <strong>{{ object.user }}</strong>
        </div>

        <h3>Projects:</h3>
        <ul>
          {% for project in object.projects.all %}
            <li>{{ project.name }} - ${{ project.price }}</li>
          {% endfor %}
        </ul>

        <h3 class="text-primary">
            Total sum: ${{ aggr_proj_sum.projects__price__sum }}
        </h3>

      {% endfor %}

    <div class="my-2">
      <a class="btn btn-success"
         href="{% url 'shop_projects:update-order' pk=pk %}">
          Update</a>

        {% if perms.shop_projects.delete_order %}
        <a class="btn btn-warning"
           href="{% url 'shop_projects:confirm-delete-order' pk=pk %}">
           Archive</a>

        {% endif %}
    </div>

  <div>
    <a class="btn btn-secondary"
       href="{% url back_url_to_all_objs %}">
       To all {{ class_name_plural }}</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/order_list.html
{% extends 'shop_projects/index.html' %}

{% block title %}
    {{ class_name_plural }}
{% endblock %}

{% block body %}
<h1>{{ class_name_plural }}:</h1>
<div>
    <ul>

        {% for object,projs_sum  in query_list %}
            <li><a
                href="{% url 'shop_projects:order-details' pk=object.pk %}">
                #{{ object.id }} by {{ object.user }}</a>
                (Total sum: <i>${{ projs_sum.projects__price__sum }}</i>)
            </li>
        {% if forloop.last %}
        <div class="my-2">
            Total orders: {{ forloop.counter }}
        </div>
        {% endif %}
        {% endfor %}
    </ul>
</div>

<a class="btn btn-primary my-2"
   href="{% url 'shop_projects:create-order' %}">
   Create new {{ class_name }}</a>

<div>
    {% include 'macros/back_to_index.html' %}
</div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/project_confirm_delete.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Archive {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Archive <code>{{ object.name }}</code></h1>
  <div class="alert alert-danger">
    Are you sure you want to archive {{ class_name }} #{{ object.pk }}
    with name <code>{{ object.name }}</code>?
  </div>

  <form class="my-2" method="post">
    {% csrf_token %}
    <input class="btn btn-warning" type="submit" value="Archive">
  </form>


  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:project-details' pk=object.pk %}">
        Back to {{ class_name }} details</a>
  </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/project_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Create {{ class_name }}
{% endblock %}

{% block body %}
    <h1>Create a new {{ class_name }}:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/project_list.html
{% extends 'shop_projects/index.html' %}

{% block title %}
    {{ class_name_plural }}
{% endblock %}

{% block body %}
    <h1>{{ class_name_plural }}:</h1>
    <div>
        <ul>
            {% for object in object_list %}
                <li><a
                    href="{% url 'shop_projects:project-details' pk=object.pk %}">
                    {{ object.name }}</a></li>
            {% endfor %}
        </ul>
    </div>


    <a class="btn btn-primary my-2"
       href="{% url 'shop_projects:create-project' %}">
       Create new {{ class_name }}</a>

    <div>
        {% include 'macros/back_to_index.html' %}
    </div>
{% endblock %}

pro_platform/shop_projects/templates/shop_projects/project_update_form.html
{% extends 'shop_projects/index.html' %}

{% block title %}
  Update {{ class_name }} #{{ object.pk }}
{% endblock %}

{% block body %}
  <h2>Update {{ class_name }} #{{ object.pk }} with name <code>{{ object.name }}</code></h2>
  <form class="my-3" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn btn-primary" type="submit" value="Update">
  </form>

  <div>
    <a class="btn btn-sm btn-info"
       href="{% url 'shop_projects:project-details' pk=object.pk %}">
      Back to {{ class_name }} details</a>
  </div>
{% endblock %}