pro_platform/auth_block/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    LoginView,
    LogoutView, RegisterView,
)
from django.contrib.auth.views import (
    # LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = "auth_block"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("me/", TemplateView.as_view(template_name="auth_block/me.html"), name="about-me"),


    path('password-reset/', PasswordResetView.as_view(template_name='auth_block/password_reset.html'),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='auth_block/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='auth_block/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='auth_block/password_reset_complete.html'),
         name='password_reset_complete'),
]

pro_platform/my_projects/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from my_projects.views import sex_age_det
from my_projects.views import car_num_det
from my_projects.views import exercise_rec
from my_projects.views import koncert_bot

app_name = "my_projects"

urlpatterns = [
    path("", TemplateView.as_view(template_name="my_projects/index.html"), name="index"),

    path("sex_age_humans_detection/", sex_age_det.image_request, name="sex_age_detection"),
    path("sex_age_humans_detection/download-img/", sex_age_det.download_image_for_predict, name="sex_age_det_img"),
    path("sex_age_humans_detection/about/", sex_age_det.render_about, name="sex_age_det_about"),

    path("exercise_recognition/", exercise_rec.video_request, name="exercise_recognition"),
    path("exercise_recognition/download-vid/", exercise_rec.download_video_for_predict, name="exercise_rec_vid"),
    path("exercise_recognition/about/", exercise_rec.render_about, name="exercise_rec_about"),

    path("koncert_bot/", koncert_bot.render_about, name="koncert_bot"),

    path("car_num_detection/", car_num_det.image_request, name="car_num_detection"),
    path("car_num_detection/download-img/", car_num_det.download_image_for_predict, name="car_num_det_img"),
    path("car_num_detection/about/", car_num_det.render_about, name="car_num_det_about"),
]

pro_platform/pro_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name='main_index'),

    path('auth/', include('auth_block.urls')),
    path('shop_projects/', include('shop_projects.urls')),
    path('my_projects/', include('my_projects.urls')),

    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

    # adding media static for url searching
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_platform/shop_projects/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views.index import ShopIndexView, get_task_info
from .views.projects import (
    ProjectsListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
)
from .views.categories import (
    CategoriesListView,
    CategoryDetailView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
)
from .views.creators import (
    CreatorsListView,
    CreatorDetailView,
    CreatorCreateView,
    CreatorUpdateView,
    CreatorDeleteView,
)

from .views.donats import (
    DonatsListView,
    DonatDetailView,
    DonatCreateView,
    DonatUpdateView,
    DonatDeleteView,
)
from .views.orders import (
    order_list_view,
    order_detail_view,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
)

app_name = "shop_projects"

urlpatterns = [
    path('', ShopIndexView.as_view(), name="index"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task-id"),

    path('projects', ProjectsListView.as_view(), name="projects"),
    path("projects/create/", ProjectCreateView.as_view(), name="create-project"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-details"),
    path("projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="update-project"),
    path("projects/<int:pk>/confirm-delete/", ProjectDeleteView.as_view(), name="confirm-delete-project"),

    path('categories', CategoriesListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category-details"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),

    path('creators', CreatorsListView.as_view(), name="creators"),
    path("creators/create/", CreatorCreateView.as_view(), name="create-creator"),
    path("creators/<int:pk>/", CreatorDetailView.as_view(), name="creator-details"),
    path("creators/<int:pk>/update/", CreatorUpdateView.as_view(), name="update-creator"),
    path("creators/<int:pk>/confirm-delete/", CreatorDeleteView.as_view(), name="confirm-delete-creator"),

    path('donats', DonatsListView.as_view(), name="donats"),
    path("donats/create/", DonatCreateView.as_view(), name="create-donat"),
    path("donats/<int:pk>/", DonatDetailView.as_view(), name="donat-details"),
    path("donats/<int:pk>/update/", DonatUpdateView.as_view(), name="update-donat"),
    path("donats/<int:pk>/confirm-delete/", DonatDeleteView.as_view(), name="confirm-delete-donat"),

    path('orders', order_list_view, name="orders"),
    path("orders/create/", OrderCreateView.as_view(), name="create-order"),
    path("orders/<int:pk>/", order_detail_view, name="order-details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="update-order"),
    path("orders/<int:pk>/confirm-delete/", OrderDeleteView.as_view(), name="confirm-delete-order"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pro_platform/templates/base.html
<!doctype html>

{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
        Base
        {% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">


    <link rel="stylesheet" href="{% static 'css/my_styles.css' %}">

</head>

<body>

{% block nav %}

{% endblock %}

<div class="container">
    {% block body %}

    {% endblock %}
</div>

<div class="container">
    {% block signature %}

    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

pro_platform/templates/index.html
{% extends 'base.html' %}

{% block title %}
Sales Shop Index
{% endblock %}


{% block nav %}
<nav class="navbar navbar-expand-sm navbar-light bg-light">

    <div class="list-group mx-2 my-2">
        <a class="list-group-item list-group-item-action list-group-item-primary"
           href="{% url 'main_index' %}">
            ProPlat
        </a>
        {% if user.is_authenticated %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:about-me' %}">
            User: {{ user.username }}
        </a>
        <a class="list-group-item list-group-item-action list-group-item-warning"
           href="{% url 'auth_block:logout' %}">
            Logout
        </a>
        {% else %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:login' %}">
            Login
        </a>
        {% endif %}
    </div>
</nav>
{% endblock %}

{% block body %}

<h1>APPs:</h1>

<div class="learning-item">
    <a href="{% url 'shop_projects:index' %}" class="learning-item__box">
    <div class="learning-item__box2">
    <div class="learning-item__title">Shop projects</div>
    <div class="learning-item__text">
    &#128640 Here are the <strong>projects</strong> and their <strong>creators</strong>
    </div>
    <div class="learning-item__text">
    &#128204 Each <strong>project</strong> belongs to a <strong>category</strong>
    </div>
    <div class="learning-item__text">
    &#128293 The <strong>user</strong> can become a <strong>creator</strong> and create a <strong>project</strong> by specifying a price
    </div>
    <div class="learning-item__text">
    &#128176 <strong>Users</strong> can buy <strong>projects</strong> and make <strong>donats</strong> for their development
    </div>
    </div>
    <br>

    <div class="learning-item__text_center">
    CLICK AND TRY!
    </div>
    </a>
</div>

<div class="learning-item my-2">
    <a href="{% url 'my_projects:index' %}" class="learning-item__box">
    <div class="learning-item__box2">
    <div class="learning-item__title">My projects</div>
    <div class="learning-item__text">
    &#128293 <strong>Detecting</strong> human faces and determining <strong>gender</strong> and <strong>age</strong> in an image
    </div>
    <div class="learning-item__text">
    &#128165 Try service for the <strong>classification</strong> of physical <strong>exercises</strong> by video
    </div>
    <div class="learning-item__text">
    &#128640 Learn about <strong>Concert Information Service</strong>
    </div>
    <div class="learning-item__text">
    &#128304 Try car number <strong>recognition service</strong>
    </div>
    </div>
    <br>

    <div class="learning-item__text_center">
    CLICK AND TRY!
    </div>
    </a>
</div>

{% endblock %}