pro_platform/auth_block/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    LoginView,
    LogoutView, RegisterView,
)
from django.contrib.auth.views import (
    # LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = "auth_block"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("me/", TemplateView.as_view(template_name="auth_block/me.html"), name="about-me"),


    path('password-reset/', PasswordResetView.as_view(template_name='auth_block/password_reset.html'),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='auth_block/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='auth_block/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='auth_block/password_reset_complete.html'),
         name='password_reset_complete'),
]

pro_platform/my_projects/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from my_projects.views import sex_age_det
from my_projects.views import car_num_det
from my_projects.views import exercise_rec
from my_projects.views import koncert_bot

app_name = "my_projects"

urlpatterns = [
    path("", TemplateView.as_view(template_name="my_projects/index.html"), name="index"),

    path("sex_age_humans_detection/", sex_age_det.image_request, name="sex_age_detection"),
    path("sex_age_humans_detection/download-img/", sex_age_det.download_image_for_predict, name="sex_age_det_img"),
    path("sex_age_humans_detection/about/", sex_age_det.render_about, name="sex_age_det_about"),

    path("exercise_recognition/", exercise_rec.video_request, name="exercise_recognition"),
    path("exercise_recognition/download-vid/", exercise_rec.download_video_for_predict, name="exercise_rec_vid"),
    path("exercise_recognition/about/", exercise_rec.render_about, name="exercise_rec_about"),

    path("koncert_bot/", koncert_bot.render_about, name="koncert_bot"),

    path("car_num_detection/", car_num_det.image_request, name="car_num_detection"),
    path("car_num_detection/download-img/", car_num_det.download_image_for_predict, name="car_num_det_img"),
    path("car_num_detection/about/", car_num_det.render_about, name="car_num_det_about"),
]

pro_platform/pro_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name='main_index'),

    path('auth/', include('auth_block.urls')),
    path('shop_projects/', include('shop_projects.urls')),
    path('my_projects/', include('my_projects.urls')),

    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

    # adding media static for url searching
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_platform/my_projects/forms.py
from django import forms

from my_projects.models import (
    ImageSexAgeDetect,
    ImageCarNumDetect,
    VideoExerciseRec,
)


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"


class ImageSexAgeDetectForm(BaseForm):
    class Meta:
        model = ImageSexAgeDetect
        fields = (
            'name',
            'InputImage',
        )


class ImageCarNumDetectForm(BaseForm):
    class Meta:
        model = ImageCarNumDetect
        fields = (
            'name',
            'InputImage',
        )


class VideoExerciseRecForm(BaseForm):
    class Meta:
        model = VideoExerciseRec
        fields = (
            'name',
            'InputVideo',
        )

pro_platform/my_projects/views/car_num_det.py
import base64
import io
import os

from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from config import CONFIG_OBJECT
from my_projects.forms import ImageCarNumDetectForm

from PIL import Image

from my_projects.views.support_funcs import get_template_names_dict
from pro_platform.settings import BASE_DIR
import requests


# make by just request
def get_prediction_by_req(url: str, json_out: dict):
    response = requests.post(url, json=json_out)
    json_input = response.json()
    return json_input


#
def image_bytes_to_str(im_path):
    with open(im_path, mode='rb') as file:
        image_bytes = file.read()
    image_str = base64.encodebytes(image_bytes).decode('utf-8')
    return image_str


def show_input_image(image_bytes):
    image = Image.open(io.BytesIO(image_bytes))
    image.show()


def save_tagged_image(image_bytes, path_tagged_image: str):
    image = Image.open(io.BytesIO(image_bytes))
    image.save(path_tagged_image)


def image_request(request):
    if request.method == 'POST':
        form = ImageCarNumDetectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            # Getting the current instance object to display in the template
            image_object = form.instance

            # Getting path for saving input image
            path_input_image = image_object.InputImage.url
            path_input_image_abs = BASE_DIR / path_input_image[1:]  # ignore first "/" in image path

            # serialization
            json_out = {}
            json_out['user'] = request.user.username
            json_out['image'] = image_bytes_to_str(path_input_image_abs)
            image_name = os.path.basename(path_input_image_abs)
            json_out['image_name'] = image_name

            # sending image to service and receiving  response with tagged image
            json_input: dict = get_prediction_by_req(f'{CONFIG_OBJECT.API_CAR_NUM_URL}/image', json_out)

            #  deserialization
            image_bytes = base64.b64decode(json_input["tagged_image"])
            detected_number = json_input['detected_number'][0]

            # create images_tagged dir if it doesnt exist
            path_tagged_dir = BASE_DIR / 'media' / 'images_tagged'
            if not os.path.exists(path_tagged_dir): os.makedirs(path_tagged_dir)

            # absolute path
            path_tagged_image = path_tagged_dir / image_name
            save_tagged_image(image_bytes, path_tagged_image)

            # relative path
            path_tagged_image_for_form = f'''/media/images_tagged/{image_name}'''

            return render(
                request,
                'my_projects/car_num_det_try.html',
                {
                    'form': form,
                    'image_object': image_object,
                    'path_tagged_image': path_tagged_image_for_form,
                    'detected_number': detected_number,
                }
            )
    else:
        form = ImageCarNumDetectForm()

    return render(
        request,
        'my_projects/car_num_det_try.html',
        {'form': form}
    )


def render_about(request: HttpRequest):
    description_dir = BASE_DIR / 'my_projects' / 'templates' / 'my_projects' / 'car_num_det_about_files'

    template_names_dict = get_template_names_dict(description_dir)

    return render(
        request,
        'my_projects/car_num_det_about.html',
        template_names_dict,
    )


def download_image_for_predict(request: HttpRequest) -> HttpResponse:
    image_path = BASE_DIR / 'media_for_tests' / 'images' / 'img_car_num.jpeg'

    with open(image_path, "rb") as f:
        return HttpResponse(
            f.read(),
            content_type="image/jpeg",
            headers={"Content-Disposition": 'attachment; filename="image_test.jpg"'},
        )

pro_platform/my_projects/views/exercise_rec.py
import base64
import io
import os

from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from config import CONFIG_OBJECT
from my_projects.forms import VideoExerciseRecForm

from PIL import Image

from my_projects.views.support_funcs import get_template_names_dict
from pro_platform.settings import BASE_DIR
import requests


# make by just request
def get_prediction_by_req(url: str, json_out: dict):
    response = requests.post(url, json=json_out)
    json_input = response.json()
    return json_input


#
def media_bytes_to_str(im_path):
    with open(im_path, mode='rb') as file:
        image_bytes = file.read()
    image_str = base64.encodebytes(image_bytes).decode('utf-8')
    return image_str


def show_input_image(image_bytes):
    image = Image.open(io.BytesIO(image_bytes))
    image.show()


def save_tagged_image(image_bytes, path_tagged_image: str):
    image = Image.open(io.BytesIO(image_bytes))
    image.save(path_tagged_image)


def video_request(request):
    if request.method == 'POST':
        form = VideoExerciseRecForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            # Getting the current instance object to display in the template
            video_object = form.instance

            # Getting path for saving input video
            path_input_video = video_object.InputVideo.url
            path_input_video_abs = BASE_DIR / path_input_video[1:]  # ignore first "/" in video path

            # serialization
            json_out = {}
            json_out['user'] = request.user.username
            json_out['video'] = media_bytes_to_str(path_input_video_abs)
            video_name = os.path.basename(path_input_video_abs)
            json_out['video_name'] = video_name

            # sending video to service and receiving  response with tagged video
            json_input: dict = get_prediction_by_req(f'{CONFIG_OBJECT.API_EX_REC_URL}/video', json_out)

            #  deserialization
            pred_type = json_input['pred_type']
            pred_count = json_input['pred_count']
            gif_bytes = base64.b64decode(json_input["tagged_gif"])

            # create videos_tagged dir if it doesnt exist
            path_tagged_dir = BASE_DIR / 'media' / 'gif_files'
            if not os.path.exists(path_tagged_dir): os.makedirs(path_tagged_dir)

            # absolute path
            gif_name = f'''{video_name.split('.')[0]}.gif'''
            path_tagged_video = path_tagged_dir / gif_name
            with open(path_tagged_video, mode='wb') as f:
                f.write(gif_bytes)  # save video to disk

            # relative path
            path_tagged_video_for_form = f'''/media/gif_files/{gif_name}'''

            return render(
                request,
                'my_projects/exercise_rec_try.html',
                {
                    'form': form,
                    'video_object': video_object,
                    'path_tagged_video': path_tagged_video_for_form,
                    'pred_type': pred_type,
                    'pred_count': pred_count,
                }
            )
    else:
        form = VideoExerciseRecForm()
    return render(
        request,
        'my_projects/exercise_rec_try.html',
        {'form': form}
    )


def render_about(request: HttpRequest):
    description_dir = BASE_DIR / 'my_projects' / 'templates' / 'my_projects' / 'exercise_rec_about_files'

    template_names_dict = get_template_names_dict(description_dir)

    return render(
        request,
        'my_projects/exercise_rec_about.html',
        template_names_dict,
    )


def download_video_for_predict(request: HttpRequest) -> HttpResponse:
    image_path = BASE_DIR / 'media_for_tests' / 'videos' / 'pull_ups_2.mp4'

    with open(image_path, "rb") as f:
        return HttpResponse(
            f.read(),
            content_type="video/mp4",
            headers={"Content-Disposition": 'attachment; filename="video_test.mp4"'},
        )

pro_platform/my_projects/views/koncert_bot.py
from django.http import HttpRequest
from django.shortcuts import redirect, render

from my_projects.views.support_funcs import get_template_names_koncert_bot_dict
from pro_platform.settings import BASE_DIR


def render_about(request: HttpRequest):
    description_dir = BASE_DIR / 'my_projects' / 'templates' / 'my_projects' / 'koncert_bot_about_files'

    template_names_dict = get_template_names_koncert_bot_dict(description_dir)

    return render(
        request,
        'my_projects/koncert_bot_about.html',
        template_names_dict,
    )

pro_platform/my_projects/views/sex_age_det.py
import base64
import io
import os

from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from config import CONFIG_OBJECT
from my_projects.forms import ImageSexAgeDetectForm

from PIL import Image

from my_projects.views.support_funcs import get_template_names_dict
from pro_platform.settings import BASE_DIR
import requests


# make by just request
def get_prediction_by_req(url: str, json_out: dict):
    response = requests.post(url, json=json_out)
    json_input = response.json()
    return json_input


#
def image_bytes_to_str(im_path):
    with open(im_path, mode='rb') as file:
        image_bytes = file.read()
    image_str = base64.encodebytes(image_bytes).decode('utf-8')
    return image_str


def show_input_image(image_bytes):
    image = Image.open(io.BytesIO(image_bytes))
    image.show()


def save_tagged_image(image_bytes, path_tagged_image: str):
    image = Image.open(io.BytesIO(image_bytes))
    image.save(path_tagged_image)


def image_request(request):
    if request.method == 'POST':
        form = ImageSexAgeDetectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            # Getting the current instance object to display in the template
            image_object = form.instance

            # Getting path for saving input image
            path_input_image = image_object.InputImage.url
            path_input_image_abs = BASE_DIR / path_input_image[1:]  # ignore first "/" in image path

            # serialization
            json_out = {}
            json_out['user'] = request.user.username
            json_out['image'] = image_bytes_to_str(path_input_image_abs)
            image_name = os.path.basename(path_input_image_abs)
            json_out['image_name'] = image_name

            # sending image to service and receiving  response with tagged image
            json_input: dict = get_prediction_by_req(f'{CONFIG_OBJECT.API_SEX_AGE_URL}/image', json_out)

            #  deserialization
            image_bytes = base64.b64decode(json_input["tagged_image"])

            # create images_tagged dir if it doesnt exist
            path_tagged_dir = BASE_DIR / 'media' / 'images_tagged'
            if not os.path.exists(path_tagged_dir): os.makedirs(path_tagged_dir)

            # absolute path
            path_tagged_image = path_tagged_dir / image_name
            save_tagged_image(image_bytes, path_tagged_image)

            # relative path
            path_tagged_image_for_form = f'''/media/images_tagged/{image_name}'''

            return render(
                request,
                'my_projects/sex_age_det_try.html',
                {'form': form, 'image_object': image_object, 'path_tagged_image': path_tagged_image_for_form}
            )
    else:
        form = ImageSexAgeDetectForm()
    return render(
        request,
        'my_projects/sex_age_det_try.html',
        {'form': form}
    )


def render_about(request: HttpRequest):
    description_dir = BASE_DIR / 'my_projects' / 'templates' / 'my_projects' / 'sex_age_det_about_files'

    template_names_dict = get_template_names_dict(description_dir)

    return render(
        request,
        'my_projects/sex_age_det_about.html',
        template_names_dict,
    )


def download_image_for_predict(request: HttpRequest) -> HttpResponse:
    image_path = BASE_DIR / 'media_for_tests' / 'images' / 'img_sex_age.jpg'

    with open(image_path, "rb") as f:
        return HttpResponse(
            f.read(),
            content_type="image/jpeg",
            headers={"Content-Disposition": 'attachment; filename="image_test.jpg"'},
        )

pro_platform/my_projects/views/support_funcs.py
from my_projects.config import file_description_list, file_description_list_koncert_bot


def get_template_names_dict(description_dir):
    template_names_dict = {}
    for filename, template_name in file_description_list:
        description_path = description_dir / filename
        with open(description_path, mode='r') as f:
            template_names_dict[template_name] = f.readlines()

    return template_names_dict


def get_template_names_koncert_bot_dict(description_dir):
    template_names_dict = {}
    for filename, template_name in file_description_list_koncert_bot:
        description_path = description_dir / filename
        with open(description_path, mode='r') as f:

            if filename == 'platforms.txt':
                platforms_paras = f.readlines()
                platforms_names = platforms_paras[0:3]
                platforms_urls = platforms_paras[3:]
                platforms_names_urls_zip = zip(platforms_names, platforms_urls)
                template_names_dict[template_name] = platforms_names_urls_zip
            else:
                template_names_dict[template_name] = f.readlines()

    return template_names_dict

pro_platform/my_projects/templates/my_projects/car_num_det_about.html
{% extends 'my_projects/index.html' %}

{% block title %}
  Car-num det about
{% endblock %}

{% block body %}
<h2>Car numbers detection service</h2>

<div class="my-4">
        <h3>General description:</h3>
        {% for paragraph in general_description_paras %}
            <p>
                {{ paragraph }}
            </p>

        {% endfor %}
</div>

<div class="my-4">
        <h3>Service functionality:</h3>
        <ul>
        {% for paragraph in service_functionality_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>Architecture:</h3>
        <ul>
        {% for paragraph in architecture_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>Project implementation:</h3>
        <ul>
        {% for paragraph in project_implementation_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>API description:</h3>
        <ul>
        {% for paragraph in api_description_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>Links to source code:</h3>
        <ul>
            <li>
                <a
                    class="btn-link my-1"
                    href="{{ links_to_source.0 }}">
                    Whole project url
                </a>
            </li>
            <li>
                <a
                    class="btn-link my-1"
                    href="{{ links_to_source.1 }}">
                    API url
                </a>
            </li>
        </ul>
    <p>
        *service implemented jointly with my fellow programmer <a href="https://github.com/pavelnebel"> "pavelnebel"</a>
    </p>
</div>

<div class="my-2">
<a class="btn btn-success"
     href="{% url 'my_projects:car_num_detection' %}">
     Back to try</a>
<a class="btn btn-warning"
   href="{% url 'my_projects:index' %}">
   Back to projects</a>
</div>
{% endblock %}

pro_platform/my_projects/templates/my_projects/car_num_det_try.html
{% extends 'my_projects/index.html' %}

{% block title %}
Image loading
{% endblock %}

{% block body %}
<div class="divs_inline">
    <div>
    Car numbers detection
    </div>
    <div>
        <div style="justify-content: flex-end">
            <a class="btn btn-info my-2"
            href="{% url 'my_projects:car_num_det_about' %}">
            About</a>
        </div>
    </div>
</div>

<div class="my-1">
<a class="btn btn-success"
   href="{% url 'my_projects:car_num_det_img' %}">
   Download image for test</a>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
     <input class="btn btn-primary" type="submit" name="predict" value="Predict!">
</form>



{% if image_object %}
<div class="my-3">
    <h3>Detected car number:  <span class="bord"><strong>{{ detected_number }}</strong></span></h3>
</div>
<div class="my-3 d-flex justify-content-center">
    <img src="{{ path_tagged_image }}" alt="connect" style="max-height:300px" width="400">
</div>
{% endif %}

<div class="my-1">
<a class="btn btn-warning"
   href="{% url 'my_projects:index' %}">
   Back to projects</a>
</div>
{% endblock %}

pro_platform/my_projects/templates/my_projects/exercise_rec_about.html
{% extends 'my_projects/index.html' %}

{% block title %}
  Exercise rec about
{% endblock %}

{% block body %}
<h2>Exercise recognition service</h2>

<div class="my-4">
        <h3>General description:</h3>
        {% for paragraph in general_description_paras %}
            <p>
                {{ paragraph }}
            </p>

        {% endfor %}
</div>

<div class="my-4">
        <h3>Service functionality:</h3>
        <ul>
        {% for paragraph in service_functionality_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>Architecture:</h3>
        <ul>
        {% for paragraph in architecture_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>Project implementation:</h3>
        <ul>
        {% for paragraph in project_implementation_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>API description:</h3>
        <ul>
        {% for paragraph in api_description_paras %}
            <li>
                <p>{{ paragraph }}</p>
            </li>
        {% endfor %}
        </ul>
</div>

<div class="my-4">
        <h3>Links to source code:</h3>
        <ul>
            <li>
                <a
                    class="btn-link my-1"
                    href="{{ links_to_source.0 }}">
                    Whole project url
                </a>
            </li>
            <li>
                <a
                    class="btn-link my-1"
                    href="{{ links_to_source.1 }}">
                    API url
                </a>
            </li>
        </ul>
</div>

<div class="my-2">
<a class="btn btn-success"
     href="{% url 'my_projects:exercise_recognition' %}">
     Back to try</a>
<a class="btn btn-warning"
   href="{% url 'my_projects:index' %}">
   Back to projects</a>
</div>
{% endblock %}

pro_platform/my_projects/templates/my_projects/exercise_rec_try.html
{% extends 'my_projects/index.html' %}

{% block title %}
video loading
{% endblock %}

{% block body %}
<div class="divs_inline">
    <div>
    Exercise recognition
    </div>
    <div>
        <div style="justify-content: flex-end">
            <a class="btn btn-info my-2"
            href="{% url 'my_projects:exercise_rec_about' %}">
            About</a>
        </div>
    </div>
</div>

<div class="my-1">
<a class="btn btn-success"
   href="{% url 'my_projects:exercise_rec_vid' %}">
   Download video for test</a>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
     <input class="btn btn-primary" type="submit" name="predict" value="Predict!">
</form>

{% if video_object %}
<div class="my-3">
    <h3>Exercise recognition result:</h3>
</div>
<table class="table table-bordered">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Exercise type</th>
        <th scope="col">Reps number</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">1</th>
        <td>{{ pred_type }}</td>
        <td>{{ pred_count }}</td>
    </tr>
    </tbody>
</table>
<div class="my-3 d-flex justify-content-center">
    <img src="{{ path_tagged_video }}" alt="connect" style="max-height:500px">
</div>
{% endif %}

<div class="my-1">
<a class="btn btn-warning"
   href="{% url 'my_projects:index' %}">
   Back to projects</a>
</div>
{% endblock %}

pro_platform/my_projects/templates/my_projects/index.html
{% extends 'base.html' %}

{% block title %}
  My projects Index
{% endblock %}


{% block nav %}
  <nav class="navbar navbar-expand-sm navbar-light bg-light">

    <div class="list-group mx-2 my-2">
      <a class="list-group-item list-group-item-action list-group-item-primary"
         href="{% url 'main_index' %}">
      ProPlat
      </a>
      {% if user.is_authenticated %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:about-me' %}">
          User: {{ user.username }}
        </a>
        <a class="list-group-item list-group-item-action list-group-item-warning"
           href="{% url 'auth_block:logout' %}">
          Logout
        </a>
      {% else %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:login' %}">
          Login
        </a>
      {% endif %}
    </div>

<!--Projects navbar-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

<!--Sex-age human detection-->
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown0"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Sex-age human detection
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'my_projects:sex_age_detection' %}">Try</a>
            <a class="dropdown-item" href="{% url 'my_projects:sex_age_det_about' %}">About</a>
          </div>
        </li>

<!--Exercise recognition-->
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown1"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Exercise recognition
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'my_projects:exercise_recognition' %}">Try</a>
            <a class="dropdown-item" href="{% url 'my_projects:exercise_rec_about' %}">About</a>
          </div>
        </li>

<!--Koncert bot-->
        <li class="nav-item">
        <a class="nav-link"
            href="{% url 'my_projects:koncert_bot' %}">
            Koncert bot
          </a>
        </li>

<!--Car num detection-->
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle"
           id="navbarDropdown2"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
            Car num detection
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'my_projects:car_num_detection' %}">Try</a>
            <a class="dropdown-item" href="{% url 'my_projects:car_num_det_about' %}">About</a>
          </div>
        </li>

      </ul>
    </div>
  </nav>
{% endblock %}


{% block body %}
<div>
<p class="h3 my-3">Projects:</p>
<ul class="list-group">
  <li class="list-group-item list-group-item-action">
    <a href="{% url 'my_projects:sex_age_detection' %}">Sex-age humans detection</a>
  </li>
  <li class="list-group-item list-group-item-action">
    <a href="{% url 'my_projects:exercise_recognition' %}">Exercise recognition</a>
  </li>
  <li class="list-group-item list-group-item-action">
    <a href="{% url 'my_projects:koncert_bot' %}">Koncert bot</a>
  </li>
  <li class="list-group-item list-group-item-action">
    <a href="{% url 'my_projects:car_num_detection' %}">Car numbers detection</a>
  </li>
</ul>
</div>

<div class="my-3">
<a class="btn btn-secondary"
   href="{% url 'main_index' %}">
   Back to APPs</a>
</div>
{% endblock %}


{% block signature %}
<div class="mt-1 mt-md-3 my-3">
  &copy; SOREN 2023
</div>
{% endblock %}

pro_platform/my_projects/templates/my_projects/sex_age_det_try.html
{% extends 'my_projects/index.html' %}

{% block title %}
Image loading
{% endblock %}

{% block body %}

<div class="divs_inline">
    <div>
    Sex-age detection
    </div>
    <div>
        <div style="justify-content: flex-end">
            <a class="btn btn-info my-2"
            href="{% url 'my_projects:sex_age_det_about' %}">
            About</a>
        </div>
    </div>
</div>

<div class="my-1">
<a class="btn btn-success"
   href="{% url 'my_projects:sex_age_det_img' %}">
   Download image for test</a>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
     <input class="btn btn-primary" type="submit" name="predict" value="Predict!">
</form>

{% if image_object %}
<div class="my-3">
    <h3>Sex-age detection result:</h3>
</div>
<div class="my-3 d-flex justify-content-center">
    <img src="{{ path_tagged_image }}" alt="connect" style="max-height:300px">
</div>
{% endif %}

<div class="my-1">
<a class="btn btn-warning"
   href="{% url 'my_projects:index' %}">
   Back to projects</a>
</div>
{% endblock %}