pro_platform/auth_block/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (
    LoginView,
    LogoutView, RegisterView,
)
from django.contrib.auth.views import (
    # LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = "auth_block"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("me/", TemplateView.as_view(template_name="auth_block/me.html"), name="about-me"),


    path('password-reset/', PasswordResetView.as_view(template_name='auth_block/password_reset.html'),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='auth_block/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='auth_block/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='auth_block/password_reset_complete.html'),
         name='password_reset_complete'),
]

pro_platform/my_projects/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from my_projects.views import sex_age_det
from my_projects.views import car_num_det
from my_projects.views import exercise_rec
from my_projects.views import koncert_bot

app_name = "my_projects"

urlpatterns = [
    path("", TemplateView.as_view(template_name="my_projects/index.html"), name="index"),

    path("sex_age_humans_detection/", sex_age_det.image_request, name="sex_age_detection"),
    path("sex_age_humans_detection/download-img/", sex_age_det.download_image_for_predict, name="sex_age_det_img"),
    path("sex_age_humans_detection/about/", sex_age_det.render_about, name="sex_age_det_about"),

    path("exercise_recognition/", exercise_rec.video_request, name="exercise_recognition"),
    path("exercise_recognition/download-vid/", exercise_rec.download_video_for_predict, name="exercise_rec_vid"),
    path("exercise_recognition/about/", exercise_rec.render_about, name="exercise_rec_about"),

    path("koncert_bot/", koncert_bot.render_about, name="koncert_bot"),

    path("car_num_detection/", car_num_det.image_request, name="car_num_detection"),
    path("car_num_detection/download-img/", car_num_det.download_image_for_predict, name="car_num_det_img"),
    path("car_num_detection/about/", car_num_det.render_about, name="car_num_det_about"),
]

pro_platform/pro_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name='main_index'),

    path('auth/', include('auth_block.urls')),
    path('shop_projects/', include('shop_projects.urls')),
    path('my_projects/', include('my_projects.urls')),

    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

    # adding media static for url searching
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_platform/auth_block/models.py
from django.db import models

# Create your models here.

pro_platform/auth_block/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm as AuthenticationFormGeneric,
    UserCreationForm as UserCreationFormGeneric,
)
from django import forms


class AuthenticationForm(AuthenticationFormGeneric):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"


class UserCreationForm(UserCreationFormGeneric):
    class Meta(UserCreationFormGeneric.Meta):
        fields = "username", "email",

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].required = True

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"

pro_platform/auth_block/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.views import (
    LoginView as LoginViewGeneric,
    LogoutView as LogoutViewGeneric,
)
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from auth_block.forms import AuthenticationForm, UserCreationForm

from .tasks import welcome_user


class LoginView(LoginViewGeneric):
    template_name = "auth_block/login.html"
    form_class = AuthenticationForm
    next_page = reverse_lazy("auth_block:about-me")


class LogoutView(LogoutViewGeneric):
    next_page = reverse_lazy("auth_block:about-me")


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "auth_block/register.html"
    success_url = reverse_lazy("auth_block:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        welcome_user.delay(self.object.pk)
        # user: AbstractUser = self.object
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user: AbstractUser = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response

pro_platform/auth_block/templates/auth_block/index.html
{% extends 'base.html' %}

{% block title %}
  My projects Index
{% endblock %}


{% block nav %}
  <nav class="navbar navbar-expand-sm navbar-light bg-light">

    <div class="list-group mx-2 my-2">
      <a class="list-group-item list-group-item-action list-group-item-primary"
         href="{% url 'main_index' %}">
      ProPlat
      </a>
      {% if user.is_authenticated %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:about-me' %}">
          User: {{ user.username }}
        </a>
        <a class="list-group-item list-group-item-action list-group-item-warning"
           href="{% url 'auth_block:logout' %}">
          Logout
        </a>
      {% else %}
        <a class="list-group-item list-group-item-action list-group-item-success"
           href="{% url 'auth_block:login' %}">
          Login
        </a>
      {% endif %}
    </div>

  </nav>
{% endblock %}


{% block body %}

  <div>
    <p class="h3 my-3">Sections:</p>
    <ul class="list-group">
      <li class="list-group-item list-group-item-action">
        <a href="{% url 'my_projects:sex_age_detection' %}">Sex-age humans detection</a>
      </li>
    </ul>
  </div>
{% endblock %}

pro_platform/auth_block/templates/auth_block/login.html
{% extends 'auth_block/index.html' %}

{% block title %}
  Login
{% endblock %}

{% block body %}

    <form method="post">
    {% csrf_token %}

      {% if form.errors %}
        <p class="alert alert-danger">
            Something is not right
        </p>
      {% endif %}

        {{ form.as_p }}

        <input type="hidden" name="next" value="{{ next }}">

      <!-- Submit button -->
      <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

      <!-- Register buttons -->
      <div class="text-center">
        <p>Not a member? <a href="{% url 'auth_block:register' %}">Register</a></p>
      </div>
    </form>

{% endblock %}

pro_platform/auth_block/templates/auth_block/me.html
{% extends 'auth_block/index.html' %}

{% block title %}
  About me
{% endblock %}

{% block body %}
  <h1>User info:</h1>
  {% if user.is_authenticated %}
    <div class="my-4">
      <ul>
      <li><p>Username: <code>{{ user.username }}</code></p></li>
      <li><p>Email: <code>{{ user.email }}</code></p></li>
    </div>
      </ul>

    <a href="{%url 'auth_block:password-reset' %}"  class="btn btn-warning">Reset password</a>
  {% else %}
    <h3>Anonymous user</h3>
  {% endif %}

{% endblock %}

pro_platform/auth_block/templates/auth_block/password_reset.html
{% extends 'auth_block/index.html' %}

{% block title %}
  Reset Password
{% endblock %}

{% block body %}

<div class="center">
	<form method="post" class="card">
		{% csrf_token %}
	    <h2 class="text-center my-3">Reset Password</h2>
		{% for field in form %}
	    		{{ field.label_tag }}
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small>
	        	{% endif %}
		{% endfor %}
		<div class="form-buttons mt-3">
			<input type="submit" value="Send" class="btn btn-primary">
			<a href="{%url 'auth_block:login' %}"  class="btn btn-warning">Cancel</a>
		</div>
	</form>
</div>

{% endblock %}

pro_platform/auth_block/templates/auth_block/password_reset_complete.html
{% extends 'auth_block/index.html' %}

{% block title %}
  Password reset complete
{% endblock %}

{% block body %}

  <div class="center">
	  <form method="post" class="card" novalidate>
	  	{% csrf_token %}
	    <h2 class="text-center">Log in to your account</h2>
		{% for field in form %}
	    		{{ field.label_tag }}
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small>
	        	{% endif %}
		{% endfor %}

		<input type="submit" value="Login" class="btn btn-primary full-width">
		<hr>
		<p class="text-center">Forgot your password <a href="{%url 'auth_block:password-reset'%}">Reset Password</a></p>
		<p class="text-center">Don't have a account? <a href="{%url 'auth_block:register'%}">Join Now</a></p>
	</form>
</div>

{% endblock %}

pro_platform/auth_block/templates/auth_block/password_reset_confirm.html
{% extends 'auth_block/index.html' %}

{% block title %}
  Password reset confirm
{% endblock %}

{% block body %}

<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>

	  {% for field in form %}
	    		{{ field.label_tag }}
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small>
	        	{% endif %}
		{% endfor %}
	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>

{% endblock %}

pro_platform/auth_block/templates/auth_block/password_reset_done.html
{% extends 'auth_block/index.html' %}

{% block title %}
  Reset Password
{% endblock %}

{% block body %}

<div class="center card">
	<h2>Reset Password</h2>
	<p>Please check your inbox and follow the instruction to reset your password.</p>
</div>

{% endblock %}

pro_platform/auth_block/templates/auth_block/register.html
{% extends 'auth_block/index.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Register">
  </form>
{% endblock %}